# Generated by Django 5.2.3 on 2026-06-05 16:15

import django.db.models.deletion
import file_manager.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagepublication',
            name='package',
        ),
        migrations.RemoveField(
            model_name='pagepublication',
            name='version',
        ),
        migrations.AddField(
            model_name='pagepublication',
            name='content_hash',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='pagepublication',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='page_publications', to='file_manager.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagepublication',
            name='path',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('zip_file', models.FileField(upload_to=file_manager.models.page_zip_upload_to)),
                ('content_hash', models.CharField(blank=True, max_length=80)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pages', to='file_manager.organisation')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('organisation', 'path')},
            },
        ),
    ]
