# Generated by Django 5.2.3 on 2026-05-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0004_seed_package_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageversion',
            name='content_hash',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='packageversion',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
