# Generated by Django 5.2.3 on 2026-05-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0005_v3_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='file_manager.package')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='file_manager.packageversion')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('package', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
